"""add assesment model

Revision ID: 6090b1fff55b
Revises: 8cb00980262f
Create Date: 2025-05-20 22:11:37.756118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6090b1fff55b'
down_revision = '8cb00980262f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('true_answer', sa.Integer(), nullable=False),
    sa.Column('false_answer', sa.Integer(), nullable=False),
    sa.Column('assessment_points', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_user_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_timestamp'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
