"""add assesment model

Revision ID: b96c576e3819
Revises: 6090b1fff55b
Create Date: 2025-05-20 22:26:54.770824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b96c576e3819'
down_revision = '6090b1fff55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wrong_answers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('questions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('ix_assessment_user_id')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('true_answer')
        batch_op.drop_column('false_answer')
        batch_op.drop_column('assessment_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_points', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('false_answer', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('true_answer', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_assessment_user_id', ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('answers')
        batch_op.drop_column('questions')
        batch_op.drop_column('wrong_answers')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
